include:
  - project: "ci/templates"
    ref: master
    file:
      - "/buildah-push.yml"

stages:
  - build

build-api-image:
  extends: .buildah-push
  stage: build
  when: manual
  variables:
    REPO: cns/granatapfel-api
    CONTAINERFILE: src/mirror/api/Dockerfile
    TAGS: "$CI_COMMIT_TAG latest"

build-syncer-image:
  extends: .buildah-push
  stage: build
  when: manual
  variables:
    REPO: cns/granatapfel-syncer
    CONTAINERFILE: src/mirror/syncer/Dockerfile
    TAGS: "$CI_COMMIT_TAG latest"
