include:
  - project: "ci/templates"
    ref: master
    file:
      - "/generic/buildah-push.yml"
      - "/generic/version-tag.yml"

stages:
  - prepare
  - build

compute-version:
  extends: .version-tag
  stage: prepare

build-api-image:
  extends: .buildah-push
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    CIKIT_REPO: cns/granatapfel
    CIKIT_CONTAINERFILE: src/mirror/api/Dockerfile
    CIKIT_TAGS: "$CIKIT_VERSION latest"

build-syncer-image:
  extends: .buildah-push
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    CIKIT_REPO: cns/granatapfel-syncer
    CIKIT_CONTAINERFILE: src/mirror/syncer/Dockerfile
    CIKIT_TAGS: "$CIKIT_VERSION latest"
